### PR TITLE
Parse the json given to the JsonSerializer

### PR DESCRIPTION
**Pull request by wahidnory**
We had an issue where String could contain "dirty" values instead of only json.
For our case there was a message regarding xdebug installed locally when we were trying to install new modules.

This resulted in an error that was kinda vague, eg. ('composer config -a -g' command failed).
After debuggin it became clear that our $string variable had extra lines in there regarding xdebug. So the json could not be unserialized there.

I tried make a general fix for the module so that others or you guys can benefit from this.

Hope it's for your liking.

### CODE REVIEW

**Comment by vovayatsyuk** [comment]
Thank you!

I wonder if it could be also fixed with `-q` option added to [runAuthCommand](https://github.com/swissup/module-marketplace/blob/master/Model/ComposerApplication.php#L83-L89)?

**Comment by wahidnory** [comment]
Just checked, and yes it also fixes the problem. 
Might be better than parsing json.

You can disregard this pull request then.

**Comment by vovayatsyuk** [comment]
Ok, I'm closing it.

Thank you for spending your time to find out what causes an issue!

**Comment by vovayatsyuk** [comment]
https://github.com/swissup/module-marketplace/commit/7595057fed7584f46df5fcbffc77ad9d3a086da7

**Pull request closed without merging**
